### ISSUE TITLE
Blocks replaced, added! 1.20.1 bug

### ISSUE THREAD

**Issue by Unleashed75** [Giggitybyte/SleepWarp#28] opened 2023-06-29 08:32 UTC
https://github.com/Giggitybyte/SleepWarp/assets/136971457/1a59ee6f-85ae-4aad-8a51-6927fecac61d
![2023-06-28_07 19 05](https://github.com/Giggitybyte/SleepWarp/assets/136971457/8a76a980-f8b3-4098-bb75-45dc6c549761)
![2023-06-28_07 19 42](https://github.com/Giggitybyte/SleepWarp/assets/136971457/6328c503-4dcc-4752-89bd-9e0ecab25c22)
![2023-06-26_21 33 58](https://github.com/Giggitybyte/SleepWarp/assets/136971457/15fa0f7c-b52d-406f-8152-050599224205)

This took a long time to track down where this problem was coming from because it didn't always happen and seemed to be random as to where it would happen. Amethyst crystals would be floating or against other blocks. Water source would pop up even after removed. Floating Bamboo in places it should never be. The dirt blocks where the most common.

This video was recorded with only `fabric-api-0.84.0+1.20.1` and with `sleepwarp-2.1.0+1.20` installed.
The bed was placed after already viewing the cave around and was on ground level above. I think this updated the chunks maybe?
I've no idea why or how your mod is doing this. The whole thing had me confused for soo long and tracking it down to your mod was just as confusing because making it do the thing was confusing too.

I like this mod. I hope it can be fixed asap

**Comment by Unleashed75** [comment] 2023-06-29 09:27
Blocks replaced and added* 1.20.1

**Comment by theinfamousmielie** [comment] 2023-07-08 20:24
I haven't had a chance to fully confirm this yet, but doing some light ruling-out with other mods made me come to the Issues page for this mod. I think I'm having a similar issue with the mod, whereby random blocks (natural or placed) are being replaced with dirt or grass blocks underground, even at extreme depths.

Nothing else seems wrong for me, but that might be just because I've not noticed yet.

I'm not 100% sure that it's this mod causing it but I do believe it started after I added a bunch of mods, one of which was Sleepwarp a few days ago, but disabling one by one sp far hasn't made a difference except for when disabling this mod (so far at least ... very scientific heheheh)

**Comment by viral32111** [comment] 2023-07-09 12:02
I'm getting this issue too.

After adding this mod to my server, multiple players reported random dirt blocks (and a single case of a few sugar canes) underground in/around their bases. The logical explanation was Enderman grief, but since there were so many blocks and many of them were inside the walls or ceilings of player bases it was very difficult to believe, so we assumed world/saving corruption. 

I later removed this mod and there were no further reports of *new* random blocks, but existing ones were still there obviously. Ledger logs on the blocks reported they were originally grass blocks then immediately turned to dirt as they were all placed underneath solid blocks.

After a quick glance at the code in [`WarpDrive.java`](/src/main/java/me/thegiggitybyte/sleepwarp/WarpDrive.java), I assume it's something to do with `tickWorld()` or more specifically `tickRandomBlock()`, so a workaround might be to disable `tick_random_block` in the configuration, but I have no idea honestly as personally I can't find any code that may be unintentionally causing this. Then again this mod is beyond my understanding 😛

**Comment by ghost** [comment] 2023-07-23 10:11
I confirm this issue, some parts of my world are getting replaced with a massive amount of dirt blocks !

**Comment by ghost** [comment] 2023-07-31 05:04
I can confirm this, I had Version 2.1.0 Installed on a Fabric 1.20.1 Server, after Sleeping farmland that was removed started reappearing, String duplicators broke and levers could float. I don't have a Video since I've already removed the mod once it became Clear something is happening. This is a serious issue that could lead to chunk corruption, please fix it!

**Comment by piebaker** [comment] 2023-08-19 00:33
+1, been trying to track down this issue forever. Real shame its this mod, its a server favourite

**Comment by Giggitybyte** [comment] 2023-09-07 08:53
Duplicate of #25; see my comment there.

**Closed as completed by Giggitybyte** 2023-09-07 08:53 UTC
Labels: bug
